name: Deploy to production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            $HOME/.cache/firebase/emulators
          key: ${{ runner.os }}-modules-v12-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: cd eisbuk-admin && yarn
      - name: Build app
        run: cd eisbuk-admin && yarn build
      - name: Deploy to firebase
        run: cd eisbuk-admin && npx firebase deploy
        env: # Or as an environment variable
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EISBUK }}
